#!/bin/bash

PY_VER="python3"

echo "Creating project..."

mkdir "$1" && cd "$1"
echo "# $1" > README.md
touch .gitignore
git init
eval $PY_VER -m venv venv
source venv/bin/activate

echo "Python project created!"
